# Generated by Django 2.1.2 on 2018-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='tabs',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
