# Generated by Django 2.1.2 on 2018-10-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181022_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='active',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'In Active')], default=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
