# Generated by Django 2.1.2 on 2018-10-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181024_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Kontakt',
        ),
    ]
